/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
    admin: AdminAuthOperations;
  };
  collections: {
    users: User;
    'upload-document': UploadDocument;
    subscription: Subscription;
    orders: Order;
    'learning-path': LearningPath;
    course: Course;
    category: Category;
    admin: Admin;
    coupons: Coupon;
    order_history: OrderHistory;
    module: Module;
    'course-content': CourseContent;
    'course-progresses': CourseProgress;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'upload-document': UploadDocumentSelect<false> | UploadDocumentSelect<true>;
    subscription: SubscriptionSelect<false> | SubscriptionSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'learning-path': LearningPathSelect<false> | LearningPathSelect<true>;
    course: CourseSelect<false> | CourseSelect<true>;
    category: CategorySelect<false> | CategorySelect<true>;
    admin: AdminSelect<false> | AdminSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    order_history: OrderHistorySelect<false> | OrderHistorySelect<true>;
    module: ModuleSelect<false> | ModuleSelect<true>;
    'course-content': CourseContentSelect<false> | CourseContentSelect<true>;
    'course-progresses': CourseProgressesSelect<false> | CourseProgressesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: 'id';
  user:
    | (User & {
        collection: 'users';
      })
    | (Admin & {
        collection: 'admin';
      });
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  fullname: string;
  username: string;
  phone?: string | null;
  dateofbirth?: string | null;
  province?: string | null;
  regency?: string | null;
  startDate?: string | null;
  endDate?: string | null;
  subscription_status?: ('active' | 'inactive') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upload-document".
 */
export interface UploadDocument {
  id: string;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription".
 */
export interface Subscription {
  id: string;
  name: string;
  duration: string;
  student?: (string | User)[] | null;
  base_price: number;
  discounted_price: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  order_number: string;
  subscription_type?: (string | null) | Subscription;
  course_item?: (string | null) | Course;
  user: string | User;
  coupon_code?: (string | null) | Coupon;
  original_price?: number | null;
  total_amount?: number | null;
  status: 'done' | 'pending' | 'cancelled';
  payment_token?: string | null;
  payment_redirect_url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course".
 */
export interface Course {
  id: string;
  name: string;
  slug?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  short_description: string;
  price?: number | null;
  subscription_allowed?: ('yes' | 'no') | null;
  category: {
    relationTo: 'category';
    value: string | Category;
  };
  duration: number;
  level?: ('beginner' | 'intermediate' | 'advanced') | null;
  thumbnail?: (string | null) | UploadDocument;
  highlight?: ('yes' | 'no') | null;
  status?: ('COMING_SOON' | 'PUBLISHED' | 'ARCHIVED') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category".
 */
export interface Category {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: string;
  code: string;
  discount_type: 'percentage' | 'fixed';
  /**
   * For percentage, enter as whole number (e.g., 20 for 20%). For fixed, enter amount.
   */
  discount_value: number;
  start_date: string;
  end_date: string;
  /**
   * Leave blank for unlimited uses
   */
  max_uses?: number | null;
  uses?: number | null;
  is_active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-path".
 */
export interface LearningPath {
  id: string;
  name: string;
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  student?: (string | User)[] | null;
  courses?:
    | {
        course_item: string | Course;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin".
 */
export interface Admin {
  id: string;
  fullname?: string | null;
  username?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_history".
 */
export interface OrderHistory {
  id: string;
  order: string | Order;
  order_number: string;
  coupon?: (string | null) | Coupon;
  status: 'done' | 'pending' | 'cancelled';
  change_type: 'create' | 'update' | 'delete';
  original_price?: number | null;
  discounted_price?: number | null;
  timestamp?: string | null;
  /**
   * User who made the change
   */
  user?: (string | null) | User;
  /**
   * Additional details about the change
   */
  details?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "module".
 */
export interface Module {
  id: string;
  title: string;
  description?: string | null;
  course?: (string | null) | Course;
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-content".
 */
export interface CourseContent {
  id: string;
  module?: (string | null) | Module;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  videoUrl?: string | null;
  attachment?: (string | null) | UploadDocument;
  enable_preview?: boolean | null;
  order_num: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progresses".
 */
export interface CourseProgress {
  id: string;
  user: string | User;
  course: string | Course;
  completedContent?:
    | {
        content?: (string | null) | CourseContent;
        completedAt?: string | null;
        id?: string | null;
      }[]
    | null;
  lastAccessedAt?: string | null;
  progressPercentage?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'upload-document';
        value: string | UploadDocument;
      } | null)
    | ({
        relationTo: 'subscription';
        value: string | Subscription;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'learning-path';
        value: string | LearningPath;
      } | null)
    | ({
        relationTo: 'course';
        value: string | Course;
      } | null)
    | ({
        relationTo: 'category';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'admin';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'coupons';
        value: string | Coupon;
      } | null)
    | ({
        relationTo: 'order_history';
        value: string | OrderHistory;
      } | null)
    | ({
        relationTo: 'module';
        value: string | Module;
      } | null)
    | ({
        relationTo: 'course-content';
        value: string | CourseContent;
      } | null)
    | ({
        relationTo: 'course-progresses';
        value: string | CourseProgress;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'admin';
        value: string | Admin;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'admin';
        value: string | Admin;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  fullname?: T;
  username?: T;
  phone?: T;
  dateofbirth?: T;
  province?: T;
  regency?: T;
  startDate?: T;
  endDate?: T;
  subscription_status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "upload-document_select".
 */
export interface UploadDocumentSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscription_select".
 */
export interface SubscriptionSelect<T extends boolean = true> {
  name?: T;
  duration?: T;
  student?: T;
  base_price?: T;
  discounted_price?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  order_number?: T;
  subscription_type?: T;
  course_item?: T;
  user?: T;
  coupon_code?: T;
  original_price?: T;
  total_amount?: T;
  status?: T;
  payment_token?: T;
  payment_redirect_url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "learning-path_select".
 */
export interface LearningPathSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  student?: T;
  courses?:
    | T
    | {
        course_item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course_select".
 */
export interface CourseSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  short_description?: T;
  price?: T;
  subscription_allowed?: T;
  category?: T;
  duration?: T;
  level?: T;
  thumbnail?: T;
  highlight?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category_select".
 */
export interface CategorySelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin_select".
 */
export interface AdminSelect<T extends boolean = true> {
  fullname?: T;
  username?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  discount_type?: T;
  discount_value?: T;
  start_date?: T;
  end_date?: T;
  max_uses?: T;
  uses?: T;
  is_active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_history_select".
 */
export interface OrderHistorySelect<T extends boolean = true> {
  order?: T;
  order_number?: T;
  coupon?: T;
  status?: T;
  change_type?: T;
  original_price?: T;
  discounted_price?: T;
  timestamp?: T;
  user?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "module_select".
 */
export interface ModuleSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  course?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-content_select".
 */
export interface CourseContentSelect<T extends boolean = true> {
  module?: T;
  title?: T;
  content?: T;
  videoUrl?: T;
  attachment?: T;
  enable_preview?: T;
  order_num?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-progresses_select".
 */
export interface CourseProgressesSelect<T extends boolean = true> {
  user?: T;
  course?: T;
  completedContent?:
    | T
    | {
        content?: T;
        completedAt?: T;
        id?: T;
      };
  lastAccessedAt?: T;
  progressPercentage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}